# Fatch data using Yahoo Finance API...
import yfinance
import pandas as pd

f_data = pd.read_csv('EQUITY_L.csv')  # All NSE Stock list...

stock_ = f_data[['SYMBOL']]  # stock symbols...

n = 0  # keep count...
for sym in stock_['SYMBOL']:
    print(n)
    try:
        data = yfinance.download(f'{sym}.NS')  # '.NS' for NSE Stock...
        data.to_csv(f'./Stocks/{sym}.csv')  # save to  'Stocks' folder...
    except Exception as e:
        print(f'{sym} ===> {e}')

    n += 1

print('Done...')
# For demo 5 stocks are shown...